uncc-hice/edukona_frontend

src/blocks/QuizListRow.jsx

This pull request refactors the quiz deletion functionality within the `QuizListRow` component. The changes enhance user feedback during the quiz deletion process by utilizing a promise toast notification.
- **Refactored Delete Quiz Logic**: 
- Replaced the traditional `try-catch` block with a `toast.promise` to provide a more user-friendly notification while deleting a quiz.
- The toast will show a pending state while the deletion is in progress.
- On successful deletion:
- a success notification is displayed.
- The updated quiz list data is fetched from the backend.
- The UI is updated to reflect changes.
- On failure, an error notification is shown.
- **Improved Code Readability and Maintainability**: 
- The refactored code reduces nesting and improves the flow of the delete operation …

Refactor Quiz Deletion with Promise Toast Notification in QuizListRow Component

---

src/pages/QuizSession.jsx

This pull request refactors the layout of the QR code display within the QuizSession component. The main changes include adjustments to the grid system to improve alignment and presentation. Below are the key modifications made in this update:
- **Code Movement**: The QR code component was relocated to a different position within the grid layout:
- It was previously nested within an additional `<Grid>` item that was not necessary.
- Now, the QR code is presented directly within the main grid item, improving its visibility and reducing unnecessary elements.
- **Text Alignment**: Ensured that the accompanying text "Scan to Join" remains centered above the QR code, enhancing user experience.
- **Overall Layout Enhancement**: These changes contribute to a cleaner, more intuitive layout, …

Prevent Text Under QR Code from Going Down as the Number of Quiz Participants Increases

---

src/blocks/EditableQuestion.jsx

This pull request introduces a new component called `EditableQuestion` that provides an interface for users to edit questions in an educational context. The component allows users to modify various attributes of a question, including the text, points, correct answer, and a list of incorrect answers.
- **New Component**: Added `EditableQuestion.jsx` that allows users to:
- Edit the text of the question.
- Specify the point value for the question.
- Update the correct answer.
- Modify a list of incorrect answers, including associated feedback.
- **State Management**:
- Utilized `useState` to manage the current question's data and its editability.
- Includes event handlers to manage input changes and updating of question data.
- **API Integration**:
- Integrated with `axios` to handle PUT …

# Create EditableQuestion Component

---

src/pages/EditQuizView.jsx

This pull request introduces major changes to the `EditQuizView` component. The updates primarily focus on simplifying the data-fetching logic, converting the component to use functional hooks more effectively, and enhancing the user interface for better user experience. Below is a detailed breakdown of the changes made:
- **Component Refactor:**
- Removed unused states and handlers (e.g., `selectedQuestion`, `handleOpen`, `handleClose`, `saveQuestion`, etc.) to streamline the component. 
- **Data Fetching Optimization:**
- Modified the logic for fetching quiz data and questions to use Promises with the `then` and `catch` methods instead of `async/await` and `useCallback`.
- Combined the fetching of quiz and questions data into a single effect using `useEffect`, reducing the number of …

Refactor and Simplify EditQuizView Component

---

src/blocks/QuizList.jsx
src/blocks/QuizListRow.jsx
src/services/apiService.js

This pull request introduces significant improvements to the QuizList component by refactoring the fetching logic and enhancing the overall structure. Key changes include:
- **Separation of Concerns**: Introduced a new service file `apiService.js` to handle API requests, which promotes better code organization and reusability.
- **Updated QuizList Component**:
- Removed direct API calls from the component logic and replaced them with the `fetchQuizzes` function from the new service.
- Changed the `quizzes` state initialization from an empty array to `null`. This allows the component to display a loading indicator while the quizzes are being fetched.
- Implemented a loading state using `CircularProgress` from Material-UI to improve user experience during data fetching.
- Updated the …

Refactor QuizList Component and Extract API Service

---

src/blocks/RecordButton.jsx
src/pages/InstructorRecordings/InstructorRecordings.jsx

This pull request updates the API endpoint URLs used in the `RecordButton` and `InstructorRecordings` components to reflect the correct structure for interacting with the recordings service. The following changes have been made:
- **Updated `RecordButton.jsx`:**
- Changed the URL for creating recordings from `https://api.edukona.com/create-recording/` to `https://api.edukona.com/recordings/create-recording/` to match the new API endpoint.
- **Updated `InstructorRecordings.jsx`:**
- Modified the URL for fetching recordings by changing it from `https://api.edukona.com/instructor-recordings/` to `https://api.edukona.com/recordings/`, ensuring it aligns with the updated API structure.
- Altered the URL for deleting recordings from `https://api.edukona.com/instructor-recordings/${selectedRecord …

Fix API Endpoint URLs for Recordings

---

src/services/apiService.js

This pull request introduces an interceptor for API responses to improve error handling for unauthorized access (HTTP 401). The following changes have been made:
- **Added Response Interceptor:** A response interceptor has been added to the `api` instance to handle errors globally.
- When an API response results in a 401 Unauthorized status:
- The token is removed from local storage to ensure the user is logged out.
- The window is redirected to the login page to prompt the user to log in again.
- **Preserved Successful Responses:** The interceptor continues to pass successful responses through unchanged, maintaining the existing functionality.
This change aims to enhance the user experience by automatically handling authentication errors and improving the security of the application.

Enhance API Response Handling with Interceptor for Unauthorized Access

---

src/blocks/ChangeQuizTitleDialog.jsx
src/blocks/QuizListRowMenu.jsx
src/services/apiService.js

This pull request introduces a series of changes aimed at improving the functionality and structure of the quiz application. The updates involve refactoring components, enhancing API service methods, and removing redundant token usage for API calls.
- **ChangeQuizTitleDialog Component**:
- Removed the `token` prop from the component signature as it is no longer needed for quiz title updates.
- Ensured that the component remains functional with the updated props.
- **QuizListRowMenu Component**:
- Removed unnecessary `token` prop from `QuizListRowMenu` component to streamline prop management.
- Refactored the `startQuiz` function to replace the previous Axios call with a new API service function `startQuizSession` for starting a quiz session.
- Improved error handling within the …

Refactor Quiz Application: Update Quiz Title Mechanism and API Integration

---

package-lock.json
package.json
src/App.js
src/blocks/CustomizedMenus.jsx
src/blocks/SummaryEditor.jsx
src/blocks/SummaryViewer.jsx
src/pages/Summary.jsx
src/services/apiService.js

This pull request introduces a new feature for managing summaries within the application. Below is a detailed breakdown of changes made:
- **Updated `App.js`:**  
- Imported the new `Summary` component to be used in the application.
- Added a new route `/summary/:summaryId` that renders the `Summary` component when the user is logged in, ensuring that unauthorized users are redirected.
- **Added `SummaryEditor.jsx`:**  
- Created a new component for editing summaries, featuring a `TextareaAutosize` for flexible text input.
- **Added `SummaryViewer.jsx`:**  
- Introduced a component to display summaries formatted in Markdown, providing a user-friendly viewing experience.
- **Created `Summary.jsx`:**  
- This component serves as the main summary page, managing the display and editing state …

Implement Summary Feature in Application

---

src/blocks/AnswerOption.jsx
src/blocks/AnswersGrid.jsx
src/blocks/QuizComponent.jsx
src/blocks/StudentAnswersGrid.jsx
src/pages/InstructorQuestionView.jsx

This PR introduces enhancements to the AnswerOption component, enabling it to visually indicate correct and incorrect answers through color highlights, animated transitions, and feedback messaging. The following changes have been made:
- **StyledButtonBase Enhancements:**  
- Added a pop-up animation effect for correct answers.
- Introduced new properties for background color (`bgcolor`) and highlight status to style the button accordingly.
- Set up a CSS transition for a smooth background color change and hover effects.
- **Color Coding for Answers:**  
- Implemented `correct_answer_color` and `incorrect_answer_color` constants to style answers based on correctness.
- Applied dynamic background colors based on the `highlight` prop.
- **Feedback Messaging:**  
- When an answer is marked …

Enhance AnswerOption Component with Highlight Features and Animations

---

src/blocks/StudentAnswersGrid.jsx
src/pages/StudentAnswerView.jsx

This pull request introduces significant optimizations and refactoring within the `StudentAnswersGrid` and `StudentAnswerView` components, enhancing the overall management of submission states and handling of skipped questions.
- **Removal of Local Storage State Checks:**
- Eliminated the `useEffect` hook in `StudentAnswersGrid` that was previously used to check local storage for existing submission states for a question at the component's mount. This simplification reduces unnecessary component re-renders and potential state inconsistencies.
- **Streamlining Submission Logic:**
- Retained the existing logic for storing submission states on failure, only in the error handling section without duplicating checks or storage actions unnecessarily.
- **Added State Management for Skipped …

Refactor Student Answer Components for Improved State Management

---

src/pages/QuizSessionResults.jsx
src/services/apiService.js

This pull request introduces a significant refactor to the quiz results fetching logic in the `QuizSessionResults` component. The main objective is to separate concerns by moving the fetching logic to a dedicated service function, enhancing code clarity and maintainability. Below are the detailed changes made:
- **Created `fetchResults` function** in `apiService.js`:
- Moved the quiz results fetching logic from the `QuizSessionResults` component to a new function.
- This function takes in `code` (the quiz session code) and `setResults` (the state setter) as parameters, and handles the API call to fetch results.
- Added error handling logic to log failures if the fetch operation encounters issues.
- **Updated `QuizSessionResults` component**:
- Removed the inline fetching logic and …

# Refactor Quiz Results Fetching Logic

---

src/blocks/QuizList.jsx
src/blocks/SignUpForm.js
src/pages/InstructorRecordings/InstructorRecordings.jsx
src/pages/Summary.jsx
src/services/apiService.js

This PR introduces improved error handling in various components and service functions by utilizing the `react-toastify` library to show error notifications to users. The following changes have been made:
- **QuizList Component Updates:**  
- Modified the `onUpdate` function to handle errors when fetching quizzes. If the fetch fails, a toast notification will display an error message.
- **InstructorRecordings Component Updates:**  
- Updated the call to `startQuiz` to include error handling, ensuring that users will be informed if there is a failure in starting the quiz, via a toast notification.
- **Summary Page Updates:**  
- Enhanced the `useEffect` hook to implement error handling when fetching summaries. If the fetch fails, users receive a toast notification indicating the failure.
- …

Enhance Error Handling Across Quiz and Summary Components

---

src/pages/InstructorRecordings/InstructorRecordings.jsx
src/services/apiService.js

This pull request introduces significant refactoring to the Instructor Recordings feature, improving code organization and making API interactions cleaner. The key changes are as follows:
- **Moved API Logic to Service Layer:**  
- Removed inline fetch logic for recordings and deletion from the `InstructorRecordings` component. 
- Introduced `fetchRecordings` and `deleteRecording` methods in the `apiService.js` file.
- **Updated API Calls:**  
- Modified the component to call `fetchRecordings` with a `setRecordings` callback instead of manually managing the API call.
- Changed the delete logic to use the new `deleteRecording` service function, which now handles both deletion and updating state by refetching recordings afterwards.
- **Improved State Management:**  
- `setRecordings` is now …

# Refactor Instructor Recordings Feature

---

src/pages/ProfilePage/General/General.jsx
src/services/apiService.js

KAN-216
This pull request updates the `General` component of the `ProfilePage` to improve the way user profile data is fetched and introduces toast notifications for error handling. Key changes include:
- **Removed Axios Dependency**: The previous implementation used Axios directly for fetching profile data.
- **Introduced ApiService Function**: Created a new function `fetchProfile` in `apiService.js` to encapsulate the profile fetching logic. This promotes code reusability and clearer separation of concerns.
- **Error Handling Enhancements**:
- Added toast notifications for error feedback when the user data fetch fails. Utilizes the `react-toastify` library.
- Improved `catch` block on fetching to handle and log errors effectively, including a 401 error that redirects to a different URL. …

Refactor Profile Fetching Logic and Introduce Toast Notifications

---

src/index.css

Corrected spaces for consistency in `body` and `code` sections. Ensuring uniform styling and readability across the CSS file for better maintenance.

Fix indentation in CSS file

---

.ebignore
Procfile
package-lock.json
package.json
server.js

This pull request implements essential files and configurations for the application, including server setup and deployment exclusions. The key changes made in this PR are as follows:
- **.ebignore File Added:**
- Introduced an .ebignore file to specify which files and directories should be ignored during deployment to Elastic Beanstalk, including:
- **PyCharm configuration:**
- `.idea`
- `.env`
- **Node.js dependencies:**
- `node_modules`
- `.pnp`
- `.pnp.js`
- **Testing files:**
- `coverage`
- **Miscellaneous:**
- `.DS_Store`
- Various environment-specific `.env` files (e.g., `.env.local`, `.env.development.local`, etc.)
- `npm-debug.log*`, `yarn-debug.log*`, `yarn-error.log*`
- Sentry Auth Token file: `.sentryclirc`
- **Procfile Added:**
- Introduced a `Procfile` to specify the command …

KAN-182: Introduction of Basic Server Configuration and Environment Setup

---

.github/workflows/deploy-to-prod.yml

Changed the Node.js version from 18 to 20 to leverage new features and improvements. Also corrected the Elastic Beanstalk environment name from 'hice-frontend-production' to 'hice-frontend-prod' to ensure deployment succeeds. Adjusted minor YAML formatting for consistency.

Update deploy workflow to use Node.js 20 and correct EB env name

---

src/pages/CreateQuiz.jsx
src/pages/InstructorQuestionView.jsx
src/pages/SettingsPage/Settings.jsx
src/services/apiService.js

KAN-213
This pull request includes significant updates to the **CreateQuiz** and **SettingsPage** components, as well as modifications to the **apiService** for a more modular and clear implementation. Below is a summary of the changes made:
- Replaced axios import with a direct import of `createQuiz` from `../services/apiService` to streamline the API call process.
- Simplified the quiz data structure by removing the nested `settings` object. Direct properties `live_bar_chart`, `timer`, `timer_duration`, `skip_question`, `skip_count_per_student`, `skip_question_logic`, and `skip_question_streak_count` are now top-level properties in the `quizData` object.
- Modified the quiz creation logic from a `try-catch` block to a promise-based `.then().catch()` method, enhancing readability and …

Refactor Quiz Creation and Settings Management

---

.github/workflows/deploy-to-prod.yml
eslint.config.mjs
src/blocks/NewQuizDialog.tsx
src/pages/CreateQuiz.jsx
src/pages/InstructorQuestionView.jsx
src/pages/InstructorRecordings/InstructorRecordings.jsx
tsconfig.json

This pull request implements a series of changes aimed at improving the functionality and reliability of the quiz creation feature. The key changes include:
- Updated `src/blocks/NewQuizDialog.tsx`:  
- Removed navigation logic during quiz creation to simplify flow and prevent unexpected redirects.  
- Updated `handleCreateQuiz` to handle quiz creation asynchronously while displaying a toast message indicating progress.
- Enhanced `src/pages/CreateQuiz.jsx`:
- Integrated a WebSocket connection to monitor quiz creation status.
- Implemented cleanup for WebSocket connection on component unmount using `useEffect`.
- Added handling for the 'quiz_creation_completed' message received from the WebSocket to proceed with creating the quiz only after receiving confirmation.
- Simplified …

KAN-188: Refactor and Improve Quiz Creation Feature

---

src/blocks/DeleteRecordingDialog.jsx
src/blocks/RecordingListRowMenu.tsx
src/pages/InstructorRecordings/Components/EditRecordingTitleDialog.tsx
src/pages/InstructorRecordings/InstructorRecordings.jsx
src/services/apiService.js
src/services/lambdaService.js
src/types/edukonaTypes.ts

This pull request introduces a new `RecordingListRowMenu` component that enhances the functionality of the recording management features for instructors. The new component provides a contextual menu to manage recordings, including options for creating quizzes, generating summaries, editing titles, and deleting recordings. Additionally, various dialogs have been integrated for a seamless user experience.
- **New Component: `RecordingListRowMenu.tsx`**
- Created a new React functional component for the recording list row menu.
- Imported icon components from MUI (`Delete`, `Edit`, `Quiz`, `Summarize`) to represent menu actions visually.
- Implemented state management for toggling dialogs (Edit Title, New Quiz, Delete Recording).
- Integrated a `GenericMenu` for rendering actions associated …

KAN-222: Implement Recording List Row Menu with Action Dialogs

---

src/JWTUserContext.tsx
src/services/apiService.js

This pull request introduces a new `JWTUserContext` component to streamline user authentication management within the application. Key changes include:
- **New User Context**: Created a context for managing user authentication state, including access token, refresh token, and user details.
- **State Management**: Implemented React state hooks to manage `accessToken`, `refreshToken`, `isLoggedIn`, and `user` data within the `UserProvider` component.
- **Login Functionality**: Added a login method to handle user login via standard credentials (username and password) with error handling for invalid credentials.
- **Google Authentication**: Integrated Google login functionality, allowing users to authenticate using their Google account.
- **Logout Functionality**: Created a logout method that …

Add JWT User Context for Authentication Management

---

src/App.js
src/JWTUserContext.tsx
src/blocks/JWTLoginForm.tsx
src/services/apiService.js

254
This PR integrates a new JWT authentication flow into the application by introducing a dedicated user context and login form for handling JWT-based logins, in addition to the existing authentication method. The following changes have been made:
- **New JWT User Context:**
- Created `JWTUserContext.tsx` which manages authentication state specific to JWT users. This includes:
- Access token and refresh token management.
- User login and logout methods.
- Google authentication handling.
- Context for sharing authentication state across components.
- **Global User Context Integration:**
- Updated `App.js` to integrate `JWTUserProvider` to wrap existing routes, ensuring that any component nested within can access JWT user state.
- Dual login methods supported: regular email/password and …

Enhance JWT Authentication Flow with New User Context and Login Form

---

src/pages/Landing/components/Contact/Contact.js
src/services/apiService.js

KAN-259
This PR includes significant changes to the Contact component and the related API service for handling contact form submissions. The changes help enhance the modularity and maintainability of the code by leveraging an external API service for form submission. Here are the details of the changes made:
- **Removed direct API call using Axios in the Contact component:**
- Eliminated the Axios import and direct usage for submitting the contact form, moving towards a more modular approach.
- **Introduced an API service function for contact form submission:**
- Added a new function `submitContactForm` in the `apiService.js` file, which handles the API call to the contact form endpoint.
- This function takes `formData` as a parameter and posts it to `https://api.edukona.com/contact-us/`. …

Refactor Contact Form Submission to Use API Service

---

src/App.js
src/JWTUserContext.tsx
src/blocks/JWTSignUpForm.tsx
src/services/apiService.js
src/styles/SignUpForm.css

KAN-255
This pull request introduces a new JWT-based signup feature to the application, enhancing the user authentication process. The following updates have been made:
- **New JWT SignUp Form**:
- Introduced a new component `JWTSignUpForm` for user registration via JWT authentication.
- The form captures user's first name, last name, email, and password, and includes password confirmation.
- Role selection has been added (Instructor/Student).
- **App Component Update**:
- Integrated the `JWTSignUpForm` within the `App.js` file, adding a new route `/jwt-signup` that renders the signup form when accessed.
- **Context Changes**:
- Updated `JWTUserContext.tsx` to include a new `signUp` function that handles the signup process.
- Integrated local storage management for `accessToken`, …

Enhance JWT Authentication with Signup Functionality

---

src/App.js
src/JWTUserContext.tsx
src/UserContext.js
src/index.js
src/layouts/Main/components/Topbar/Topbar.js
src/services/apiService.js

This PR includes various improvements and changes to the JWT authentication handling and the User Context functionalities. The major modifications are as follows:
- **Modified Imports**:
- Updated the import statements in `App.js` and other files to be more consistent and clean by removing unnecessary `React` import.
- **Improved User Context Management**:
- Utilized a helper function, `getUserLocalStorage`, in `JWTUserContext.tsx` to fetch the user ID from local storage as an integer.
- Adjusted the initial state of `accessToken`, `refreshToken`, and `user` to directly read from local storage, improving the efficiency of the User Provider initialization.
- Cleaned up the `reset` function to also remove user data from local storage upon logout.
- **Streamlined Login Logic**:
- Refactored …

KAN-261: Enhance JWT Authentication and User Context Management

---

src/pages/InstructorQuestionView.jsx

This pull request introduces significant enhancements to the `InstructorQuestionView` component, particularly in the management of quiz-related state variables.
- **State Management Refactor**:
- Replaced the previous settings state object with individual quiz state variables to improve clarity and maintainability of state management.
- Added a new state variable for `quiz`, which holds the current quiz details.
- Updated user count management by assigning it to a state variable using `setUserCount`.
- **WebSocket Data Handling**:
- Enhanced data handling from WebSocket responses by adding support for a new response type: `quiz_details`.
- On receiving `quiz_details`, the component now updates the quiz state and user count appropriately.
- Added console logging for debugging purposes to …

KAN-269: Refactor InstructorQuestionView: Quiz State Management Improvement

---

src/blocks/QuizListRow.jsx
src/pages/EditQuizView.jsx
src/services/apiService.js

KAN-263
This PR refactors the `QuizListRow` and `EditQuizView` components to utilize a centralized API service for quiz-related operations. The changes enhance code maintainability and readability by encapsulating API calls in dedicated service functions, minimizing direct HTTP requests within the components. Here are the key updates included in this PR:

Refactor Quiz Management Functions to Use API Service

---

src/pages/InstructorQuestionView.jsx
src/pages/InstructorRecordings/InstructorRecordings.jsx
src/pages/JoinQuiz.jsx
src/pages/QuizSession.jsx
src/pages/StudentAnswerView.jsx
src/services/apiService.js

KAN-272
- **Overview**: This pull request introduces a series of updates aimed at improving the management of WebSocket connections within the application by utilizing custom hooks for better reusability and maintainability.
- **Changes Made**:
- **Refactored WebSocket Connections**: The `useWebSocket` logic has been encapsulated into dedicated hooks, enhancing readability and separation of concerns.
- Created custom hooks:
- `useRecordingWebSocket`
- `useStudentAnswerWebSocket`
- `useQuizSessionWebSocket`
- `useJoinQuizWebSocket`
- **Component Modifications**:
- **InstructorQuestionView**:
- Switched to `useQuizSessionWebSocket` for handling WebSocket connections.
- **InstructorRecordings**:
- Utilized `useRecordingWebSocket` instead of `useWebSocket` directly.
- **JoinQuiz**:
- …

Refactor WebSocket Connections to Custom Hooks

---

src/services/apiService.js
src/services/lambdaService.js

This pull request introduces improvements to the authentication mechanism in the `lambdaService.js` file. The updates ensure that the service handles token management more effectively by including functions that refresh tokens and generate authorization headers based on available tokens. The code is now more maintainable and secure. Below are the key changes made:
- **Introduced `getAuthHeader` Function**:  
- This function checks for the existence of `jwtAccessToken` and `token`, returning the appropriate authorization header format.
- **New `topupTokenAndRun` Functionality**:  
- A new helper function to refresh the access token if necessary before executing any promise-based API call.
- This function retrieves the `refreshToken` from `localStorage` and attempts to refresh the …

Enhance Authentication Handling in Lambda Service

---

package-lock.json
package.json

This commit adds the eslint-plugin-storybook package to both package.json and package-lock.json. This plugin helps ensure consistent and error-free code quality in Storybook configurations and stories.

Add eslint-plugin-storybook dependency

---

tsconfig.json

Added exclusions for `node_modules` and story files (`.stories.ts` and `.stories.tsx`) to optimize TypeScript compilation. This ensures unnecessary files are ignored, improving build performance and maintainability.

Refine tsconfig.json to include exclusions for stories.

---

public/mockServiceWorker.js
src/blocks/GenericMenu.jsx
src/blocks/RecordingListRowMenu.tsx
src/stories/Configure.mdx
tsconfig.json

This pull request introduces a series of code enhancements and structural improvements across various components, specifically focusing on the `mockServiceWorker.js`, `GenericMenu.jsx`, and `RecordingListRowMenu.tsx` files. The changes primarily include code style consistency, addition of new prop handling, and improved event handling mechanisms.
- **mockServiceWorker.js:**
- Improved code consistency by adding missing semicolons throughout.
- Enclosed event listeners and function bodies with consistent brackets (`{}`) to enhance readability and prevent potential errors.
- Ensured all return statements are clear and consistently formatted, improving the clarity of function flows.
- **GenericMenu.jsx:**
- Enhanced the `GenericMenu` component by adding `isOpen` and `setIsOpen` props to …

KAN-286: Refactor Mock Service Worker and Menu Components

---

src/InstructorContext.tsx
src/JWTUserContext.tsx
src/hooks/useWebSocketWithTokenRefresh.ts
src/pages/InstructorRecordings/InstructorRecordings.jsx
src/services/apiService.js

KAN-311
This Pull Request introduces enhancements in error handling and token management across various components of the application. The key changes include improved error logging and ensuring consistent handling of API responses. Below are the details of the changes made:
- **InstructorContext.tsx**:
- Wrapped the `fetchCourses` function in a `catch` block to log any errors during the fetching of courses.
- **JWTUserContext.tsx**:
- Added a `try-catch` block in the `timeUntilRefresh` function to gracefully handle potential errors when parsing the JWT. Now, if an error occurs, it logs the issue and returns `0` to avoid breaking the application.
- **useWebSocketWithTokenRefresh.ts**:
- Wrapped the token validation and refresh logic in a `try-catch` block to handle any errors that arise …

## Improve Error Handling and Token Management

---

src/pages/StudentAnswerView.jsx

This PR contains significant updates to the `StudentAnswerView` component. The key changes are:
- **Removed `skipPowerUp` state**: The state for handling the skip power-up feature has been eliminated, simplifying the component's state management.
- **Removed handling of skip power-up actions**: The conditions and notifications associated with granting and using the skip power-up have been completely removed from the component logic, leading to a cleaner and more maintainable codebase.
- **Simplified conditional rendering**: The conditional rendering for showing the skip power-up button has been streamlined. It now simply checks for the submission status without the skip power-up condition, improving overall component readability and flow.
These changes contribute to a more focused …

KAN-283: Refactor StudentAnswerView Component to Remove Skip Power Up Functionality

---

src/WebSocketClient.ts
src/blocks/QuestionAnswerComponent.jsx
src/blocks/StudentAnswersGrid.jsx
src/blocks/StudentGrid.jsx
src/pages/JoinQuiz.jsx
src/pages/JoinQuizStudent.tsx
src/pages/QuizSession.jsx
src/pages/StudentAnswerView.jsx

This pull request introduces a new `WebSocketClient` class to encapsulate the functionality required for establishing and managing WebSocket connections in our application. The goal is to provide a more robust solution for handling connections, message sending, and reconnections while ensuring that various components can interact with the WebSocket without duplicating logic.
- **New File: WebSocketClient.ts**
- Created a new file containing the `WebSocketClient` class, which manages WebSocket connections and facilitates message handling.
- Added connection state management using an enumerated type `ConnectionState` to track the status of the WebSocket.
- Implemented the `attemptReconnect` method to handle reconnection attempts with exponential backoff.
- Added methods for handling errors, …

[KAN-340] Quiz Reconnects

---

src/App.js
src/UserContext.tsx
src/blocks/Navbar.jsx
src/pages/StudentAnswerView.jsx
src/services/apiService.js
src/services/lambdaService.js

This pull request introduces several key changes that enhance token management, improve WebSocket client functionality, and refine user interactions within the application. The changes aim to streamline the authentication process, improve error handling, and allow for more robust handling of WebSocket events. Below is a detailed list of changes made:
- **Renamed token function:** Updated `refreshAccessToken` to `forceTokenRefresh` to better reflect its functionality.
- **Centralized token refresh logic:** Introduced a global error handler to manage authentication errors and ensure a consistent user experience during token refresh failures.
- **Streamlined refresh flow:** Implemented a promise queue to manage failed API calls while the token is being refreshed. This prevents subsequent API …

[KAN-342] refactor: Improve Token Management & WebSocket Client Enhancements
