uncc-hice/edukona_frontend

- src/blocks/CustomizedMenus.jsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
This PR implements a new feature that allows users to generate a summary for a recording directly from the customized menus. Below are the details of the changes made:
- **Enhanced `CustomizedMenus` Component**:
- Imported a new icon, `SummarizeIcon`, to visually represent the generate summary action.
- Added the `handleGenerateSummary` function to the component props to enable summary generation through the menu.
- Created a new menu item labeled 'Generate Summary' which, upon clicking, triggers the summary generation for the recording.
- Wrapped the new menu item in a click handler to stop propagation and properly close the menu.
- **Updated `InstructorRecordings` Component**:
- Introduced the `handleGenerateSummary` function which sends a POST request to a specified API endpoint for …
> Add Summary Generation Feature to Customized Menus

- src/blocks/GenericMenu.jsx
This PR introduces a new `GenericMenu` component to the project. The component utilizes Material-UI's styling and menu components to create a customizable menu that can be used across the application.
- **New Component Creation**: 
- Added a new file `GenericMenu.jsx` under the `src/blocks` directory.
- **Imports**: 
- Imported necessary components from React and Material-UI, including `Button`, `Menu`, and `KeyboardArrowDownIcon`.
- **Styled Menu Component**:
- Created a customized `StyledMenu` using Material-UI's `styled` API to allow for additional styling.
- Defined styles for:
- Paper root (borderRadius, margin, minWidth, color, boxShadow).
- Menu items (padding and active state styles).
- **State Management**:
- Implemented local state using `React.useState` to manage the anchor …
> Add GenericMenu Component

- src/pages/EditQuizView.jsx
This pull request implements an improved rendering of incorrect answers for quizzes in the EditQuizView component. The changes are aimed at providing clearer information and better organization of incorrect answers, including associated feedback. The modifications made include the following:
- **Revised Incorrect Answers Section**: 
- Previous display method for incorrect answers was updated from a single line to a more structured layout.
- Each incorrect answer now displays both the answer and its associated feedback, enhancing clarity for users.
- The styling has been adjusted to use a flexbox layout, making the components easier to read.
- **Improved User Experience**:
- By separating each incorrect answer into its own paragraph, users can quickly identify and review feedback provided …
> Enhance Incorrect Answers Display in EditQuizView

- src/blocks/ChangeQuizTitleDialog.jsx
- src/services/apiService.js
This pull request refactors the title updating logic in the `ChangeQuizTitleDialog` component to enhance code maintainability and separation of concerns by utilizing a dedicated API service function. The following changes were made:
- **Removed Axios Direct Call**: Removed the direct Axios call for updating the quiz title from the component logic.
- **Introduced `updateQuizTitle` Service Function**: 
- Added a new function `updateQuizTitle` in `apiService.js` to handle the API request for updating quiz titles.
- This function includes error handling and logging to improve reliability and debugging.
- **Updated `ChangeQuizTitleDialog` component**: 
- Replaced the Axios call in the `updateTitle` function with a call to the newly created `updateQuizTitle` service function.
- Kept the same …
> Refactor Quiz Title Update Logic to Use Service Function

- package-lock.json
- src/blocks/QuizList.jsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
KAN-197
This pull request introduces improvements to the `QuizList` and `InstructorRecordings` components, specifically in handling cases where there are no quizzes or recordings available. The updates enhance user experience by clearly indicating empty states. 
- **Empty State Handling**:
- Added a condition to check if the `quizzes` array is empty.
- If empty, a centered message `No Quizzes` is displayed to inform the user.
- This prevents rendering an empty list and provides a clearer communication to the user.
- **Empty State Handling**:
- Introduced similar logic for handling recordings by checking if the `recordings` array is empty.
- If empty, a centered message `No Recordings` is displayed to inform the user.
- Users will now see a clear message instead of an empty table.
- …
> Enhance Quiz and Recording List UI to Handle Empty States

- src/blocks/DeleteRecordingDialog.jsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
This PR introduces a new component for deleting recordings, enhancing the user interface and experience. The following changes have been made:
- **DeleteRecordingDialog Component**: A new modal dialog for confirming recording deletions has been created with the following features:
- Uses Material-UI components for consistent styling and functionality.
- Displays a confirmation message asking users to confirm deletion.
- Integrates success/error notifications with `react-toastify` upon deletion action.
- Calls `deleteRecording` from the API service to handle the delete operation.
- **InstructorRecordings Page**: 
- Imported the `DeleteRecordingDialog` component.
- Removed the inline deletion confirmation dialog code and replaced it with the new reusable `DeleteRecordingDialog` component.
- …
> KAN-219: Add Delete Recording Dialog Component

- .ebextensions/https-single-instance.config
Renamed the command to start nginx explicitly before reloading it. This ensures nginx is running before attempting a reload, preventing errors during deployment.
> Update nginx commands in AWS Elastic Beanstalk config

- src/pages/InstructorRecordings/InstructorRecordings.jsx
This pull request refactors the placement of the `DeleteRecordingDialog` component in the `InstructorRecordings` component to improve the control flow and enhance user experience.
- **Moved the `DeleteRecordingDialog`:**
- Previously, the dialog was nested within the `recordings.map` function, which could lead to improper behavior or rendering issues.
- The dialog component is now placed outside of the `recordings.map`, which allows for better management of the dialog's state and selected recording.
> Refactor DeleteRecordingDialog Placement in InstructorRecordings Component

- src/blocks/CustomizedMenus.jsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
This pull request focuses on refactoring the `CustomizedMenus` and `InstructorRecordings` components to improve code organization, reduce complexity, and eliminate unused state management. Below are the specific changes made:
- Removed the `setSelectedRecording` prop from `CustomizedMenus` function parameters as it was no longer utilized.
- Eliminated the line that sets the selected recording ID in the `handleClick` function since it's no longer applicable in the refactored logic.
- Replaced the state management for `openNewRecording` with `openNewQuiz`, as the dialog now corresponds to a new quiz creation process instead of a recording.
- Removed the state variable `selectedRecording` which was previously used to hold the ID of the selected recording as it has been deprecated in favor of …
> KAN-226: Refactor CustomizedMenus and InstructorRecordings components

- src/pages/InstructorRecordings/Components/AccordionQuizzes.tsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
- src/services/apiService.js
This PR introduces a new component called `AccordionQuizzes` which dynamically fetches and displays quizzes associated with instructor recordings. This enhances the functionality of the `InstructorRecordings` page by providing a cleaner and more organized way to present quiz information related to each recording.
- **New Component Creation**:
- Created `AccordionQuizzes.tsx` in the `InstructorRecordings/Components` directory.
- Utilizes Material-UI's Accordion for a collapsible section that displays quizzes.
- **Data Fetching**:
- Integrates with the `axios` library to fetch quizzes from the Edukona API based on the provided recording ID.
- Fetching occurs only when the accordion is expanded for the first time to optimize performance.
- **State Management**:
- Manages state for `quizzes`, …
> Add AccordionQuizzes Component for Recording Quizzes

- src/blocks/DeleteQuestionDialog.jsx
- src/blocks/EditableQuestion.jsx
- src/services/apiService.js
KAN-262
This pull request refactors the `DeleteQuestionDialog` component to use a dedicated API service for deleting questions. The following changes have been made:
- **Removed axios import**: The axios library is no longer directly imported in the `DeleteQuestionDialog.jsx` file, promoting a cleaner separation of concerns.
- **Introduced deleteQuestion service**: A new service method `deleteQuestion` has been added to the `apiService.js` file. This method encapsulates the API call to delete a question, improving code readability and maintainability.
- **Updated handleDelete method**: The `handleDelete` function in the `DeleteQuestionDialog` now uses the new `deleteQuestion` method to handle deletion operations, enhancing the modularity of the code.
- **Removed token dependency**: The …
> # Refactor DeleteQuestionDialog to Use API Service

- src/pages/InstructorRecordings/Components/AccordionQuizzes.tsx
- src/pages/InstructorRecordings/Components/RecordingListRow.tsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
This pull request includes significant refactoring of the AccordionQuizzes component and introduces a new RecordingListRow component for better organization and clarity. The following changes were made:
- **Removed Prop `onChange`:** The `onChange` prop is no longer necessary and has been removed from the `AccordionQuizzesProps` interface.
- **Introduced `handleFetchQuizzes` Method:** A new method to handle fetching quizzes from the API was added. This centralizes the fetching logic.
- **Simplified `useEffect` Logic:** The effect now only checks if the accordion is expanded and fetches quizzes only if they have not been loaded previously.
- **Use Fetch Method Directly in `useEffect`:** The previous fetch logic was moved into the new `handleFetchQuizzes` method to keep the effect cleaner. …
> KAN-240: Refactor AccordionQuizzes component and implement RecordingListRow

- package-lock.json
- package.json
This commit removes the `eslint-plugin-storybook` package from both `package.json` and `package-lock.json`, as it is no longer needed. Additionally, unused `dev` flags in `package-lock.json` for various dependencies were cleaned up to streamline the lock file.
> Remove eslint-plugin-storybook and unused dev dependencies

- src/blocks/QuizListRowMenu.jsx
KAN-310
This pull request includes changes to `src/blocks/QuizListRowMenu.jsx` to improve the user experience by ensuring the actions menu closes after an action is selected. The most important changes include adding state management for the actions menu and modifying `MenuItem` components to close the menu upon selection.
State management improvements:
* Added a new state variable `actionsMenuOpen` to manage the open/close state of the actions menu.
User experience improvements:
* Modified the `GenericMenu` component to accept `isOpen` and `setIsOpen` props for controlling the menu's state.
* Updated `MenuItem` components to close the actions menu after performing their respective actions (`startQuiz`, `setEditTitleOpen`, `viewQuestions`, `deleteQuiz`).ents to the interactions within the …
> Enhance Quiz Actions Menu Interaction

- src/pages/InstructorRecordings/Components/RecordingDuration.tsx
- src/pages/InstructorRecordings/Components/RecordingListRow.tsx
- src/pages/InstructorRecordings/InstructorRecordings.jsx
- src/types/edukonaTypes.ts
KAN-307
This pull request introduces a new component for displaying the duration of recordings. The following changes were made to enhance the Instructor Recordings page:
- **Added `RecordingDuration` Component**:  
- Created a new file `RecordingDuration.tsx` that formats and displays the duration of recordings in a readable format (e.g., `1h 30m 15s`).
- Handles the case when the duration is `0` by displaying `--`.
- Uses Material-UI's `Typography` for consistent styling.
- **Updated `RecordingListRow` Component**:  
- Imported the newly created `RecordingDuration` component.
- Added `RecordingDuration` to the table, replacing the previously allocated space with appropriate width adjustments for all columns.
- Adjusted the layout of the `TableCell`s to appropriately allocate space for …
> KAN-307: Add Recording Duration Component and Update Recording List

- src/blocks/RecordingListRowMenu.tsx
- src/services/apiService.js
KAN-293
This pull request introduces functionality for downloading the transcript of a recording in the `RecordingListRowMenu` component. The following enhancements and changes have been made:
- **Added Transcript Download Capability:**
- Introduced a new function `handleGetTranscript` that fetches the transcript for a given recording using the new API endpoint.
- The fetched transcript is converted into a downloadable text file format.
- A dynamic filename is generated for the transcript based on the recording title.
- Utilizes a temporary anchor (`<a>`) element to trigger the download programmatically.
- Proper error handling and user notifications are added using the `toast` library to notify users in case of failure.
- **Updated Imports and Menu Structure:**
- Added `Download` icon …
> # Enhance Recording List with Transcript Download Functionality

- src/blocks/RecordingListRowMenu.tsx
- src/pages/InstructorRecordings/Components/ChangeRecordingCourseDialog.tsx
- src/services/apiService.js
- src/types/edukonaTypes.ts
This pull request introduces the ability to change the course associated with a recording within the Recording List component. The notable changes include the addition of new UI elements and backend functionality to support this feature.
- **Modification of `RecordingListRowMenu.tsx`:**  
- Imported the `SwapHoriz` icon from `@mui/icons-material`.  
- Added state management for the new change course dialog.  
- Introduced a new menu item for changing the course of a recording.  
- Added the `ChangeRecordingCourseDialog` component to manage the course-switching UI.
- **Creation of `ChangeRecordingCourseDialog.tsx`:**  
- Implemented a dialog component to allow selecting a new course for the recording.  
- Integrated user feedback through toast notifications on success or failure of the API …
> [KAN-306] Add Change Course Functionality to Recording List

- src/blocks/EditableQuestion.jsx
This PR refines the layout of the Editable Question component by making several key adjustments to form controls and overall structure. The changes improve usability and accessibility. Below is a summary of the modifications made:
- **Imports**:
- Added `Divider` to the imports from `@mui/material` for better visual separation of answers.
- **FormControl Adjustments**:
- Changed the `FormControl` element for the question text field to have `fullWidth` to utilize the available space better.
- Updated the `FormControl` for the correct answer field to also have `fullWidth` to maintain a consistent layout.
- **Layout Improvements for Incorrect Answers**:
- Reorganized the layout for the incorrect answers section:
- Added a `Divider` between the different answer fields to improve readability …
> [KAN-320] Enhance Editable Question Component Layout

- src/JWTUserContext.tsx
This pull request contains several key improvements to the `JWTUserContext` component related to token handling and user login state management:
- **Updated isLoggedIn State Initialization**: 
- Changed the initialization of the `isLoggedIn` state to `!!accessToken`, directly reflecting the presence of an access token rather than using a comparison to `null`.
- **Refined useEffect for Access Token**: 
- Simplified the logic within the `useEffect` hook that listens to changes in the `accessToken` state.
- Removed unnecessary checks against `null` and encapsulated the setting of the `isLoggedIn` state and local storage updates.
- Added an `else` condition to call the `reset` function when `accessToken` is absent.
- **Streamlined Token Storage for Refresh Token**: 
- Updated the logic in the …
> [KAN-331] Refactor JWTUserContext Component for Improved Token Management

- src/blocks/RecordingListRowMenu.tsx
- src/services/apiService.js
This pull request introduces a new feature that allows users to download recordings directly from the Recording List Row Menu. The following changes have been made to enhance functionality and user experience:
- **Added Download Recording Functionality:**
- A new API endpoint to download recordings has been integrated into the `apiService`.
- Implemented the `handleDownloadRecording` function in the `RecordingListRowMenu` component to facilitate downloading recordings.
- **UI Enhancements:**
- A new menu item has been added for downloading recordings, featuring a music video icon for easy recognition.
- The 'Download Recording' menu item is now functional and invokes the new download functionality upon click.
- **Improved Error Handling:**
- Added toast notifications to provide feedback …
> [KAN-315] Add Download Recording Feature to Recording List Row Menu
